/**
 * WhatsApp Integration Utilities
 * Functions to format and share content via WhatsApp
 */

import { Linking } from 'react-native';

/**
 * Format bill text for WhatsApp sharing
 */
export function formatBillForWhatsApp(
  shopName: string,
  items: Array<{ name: string; quantity: number; price: number }>,
  total: number,
  paymentType: 'cash' | 'udhaar',
  date: Date = new Date()
): string {
  const dateStr = date.toLocaleDateString('en-US', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });

  let billText = `🏪 DukaanPro - ${shopName}\n`;
  billText += `📅 Date: ${dateStr}\n`;
  billText += `─────────────────\n`;

  // Add items
  items.forEach(item => {
    const itemTotal = item.quantity * item.price;
    billText += `${item.name} x${item.quantity} = Rs.${itemTotal}\n`;
  });

  billText += `─────────────────\n`;
  billText += `💰 Total: Rs.${total}\n`;
  billText += `✅ Payment: ${paymentType === 'cash' ? 'Cash' : 'Udhaar'}\n`;
  billText += `Shukriya! 🙏`;

  return billText;
}

/**
 * Share bill via WhatsApp
 */
export async function shareBillViaWhatsApp(
  phoneNumber: string,
  billText: string
): Promise<boolean> {
  try {
    // Encode message
    const encodedMessage = encodeURIComponent(billText);

    // Format phone number (remove special characters, add country code if needed)
    let formattedPhone = phoneNumber.replace(/\D/g, '');
    if (!formattedPhone.startsWith('92')) {
      // Assume Pakistan number if no country code
      if (formattedPhone.startsWith('0')) {
        formattedPhone = '92' + formattedPhone.substring(1);
      } else {
        formattedPhone = '92' + formattedPhone;
      }
    }

    const whatsappUrl = `whatsapp://send?phone=${formattedPhone}&text=${encodedMessage}`;

    // Check if WhatsApp is available
    const canOpen = await Linking.canOpenURL(whatsappUrl);
    if (canOpen) {
      await Linking.openURL(whatsappUrl);
      return true;
    } else {
      console.warn('WhatsApp is not installed');
      return false;
    }
  } catch (error) {
    console.error('Error sharing bill via WhatsApp:', error);
    return false;
  }
}

/**
 * Send payment reminder via WhatsApp
 */
export async function sendPaymentReminder(
  phoneNumber: string,
  customerName: string,
  amount: number,
  shopName: string
): Promise<boolean> {
  try {
    const reminderText = `Hi ${customerName},\n\nThis is a reminder from ${shopName} about your pending payment of Rs.${amount}.\n\nPlease settle the payment at your earliest convenience.\n\nThank you! 🙏`;

    return shareBillViaWhatsApp(phoneNumber, reminderText);
  } catch (error) {
    console.error('Error sending payment reminder:', error);
    return false;
  }
}

/**
 * Format and share report via WhatsApp
 */
export async function shareReportViaWhatsApp(
  phoneNumber: string,
  shopName: string,
  totalSales: number,
  totalProfit: number,
  totalTransactions: number,
  period: 'today' | 'week' | 'month'
): Promise<boolean> {
  try {
    let periodText = 'Today';
    if (period === 'week') periodText = 'This Week';
    if (period === 'month') periodText = 'This Month';

    const reportText = `📊 ${shopName} - Sales Report (${periodText})\n\n` +
      `💰 Total Sales: Rs.${totalSales}\n` +
      `📈 Total Profit: Rs.${totalProfit}\n` +
      `🔢 Transactions: ${totalTransactions}\n\n` +
      `Generated by DukaanPro 📱`;

    return shareBillViaWhatsApp(phoneNumber, reportText);
  } catch (error) {
    console.error('Error sharing report:', error);
    return false;
  }
}
